# kubectl.exe create deployment --name test --image=httpd:latest --port=80
---
apiVersion: v1
kind: Namespace
metadata:
  name: deploy-app 

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-myapp
  namespace: deploy-app
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:latest 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: deploy-myapp-svc
  namespace: deploy-app
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80