apiVersion: v1
kind: Secret
metadata:
  name: mysql-app-admin-secret
  namespace: database
type: Opaque
data:
  password: cmVkaGF0MTIz   
  
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-app-user-secret
  namespace: database
type: Opaque
data:
  password: ZmxlY3RyYWc=
  user: ZGJ1c2Vy