apiVersion: v1
kind: Pod
metadata:
  name: affinity-check
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: affinity-check
    image: nginx:latest
    resources:
      limits:
        memory: "4096Mi"
        cpu: "2000m"
    ports:
      - containerPort: 80
  affinity:
    nodeAffinity:   
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: pods_seclector_basis_app
            operator: In
            values:
            - mgmt
            - webapp