apiVersion: v1
kind: Pod
metadata:
  name: load-gen
  labels:
    app.kubernetes.io/name: load-gen
spec:
  containers:
  - name: load-gen
    image: busybox
    command: ["/bin/sh", "-c", "while sleep 0.01; do wget -q -O- http://php-apache; done"]
