apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-sts
spec:
  selector:
    matchLabels:
      app: mongoapp
  serviceName: mongo-svc
  replicas: 2
  template:
    metadata:
      labels:
        app: mongoapp
    spec:
      volumes:
      - name: mongo-data
        persistentVolumeClaim: 
          claimName: mongo-data-pvc
      containers:
      - name: mogngoapp
        image: mongo:latest
        ports:
        - containerPort: 27017
          name: mongo-port
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        env: 
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongouser 
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: flectrag123   

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc
  namespace: default
  labels:
    app: mongoapp
spec:
  storageClassName: nfs-storage-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: default
spec:
  selector:
    app: mongoapp
  clusterIP: none
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: 27017 
    nodePort: 32707