---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-app-secret 
  namespace: wordpress-app
type: Opaque
data:
  password: ZmxlY3RyYWc=
  user: d29yZHByZXNz

---
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /kubedata/wordpress
    server: 172.31.11.245

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-app-data0
  namespace: wordpress-app
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app
  namespace: wordpress-app
  labels:
    app: wordpress
    apptype: phpapp
spec:
  selector:
    matchLabels:
      app: wordpress
      apptype: phpapp
  template:
    metadata:
      labels:
        app: wordpress
        apptype: phpapp
    spec:
      volumes:
      - name:  wpdatastore
        persistentVolumeClaim:
          claimName: wordpress-app-data0
      containers:
      - name: wordpress-app
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-db-svc.worpress-app.svc.cluster.local
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-app-secret
              key: user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-app-secret
              key: password      
        - name: WORDDPRESS_DB_NAME
          value: wpdata      
        resources:
          requests: 
            memory: "300Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wpdatastore
          mountPath: /var/www/html/

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-app-svc
  namespace: wordpress-app
spec:
  selector:
    app: wordpress
  type: NodePort
  ports:
  - port: 80
    targetPort: 80